/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

public class App {

    public static void main(String[] args) throws Exception {
        MockHttpServletRequest mockRequest;
        boolean interceptResult;
        Object handlerObj = new Object();

        MockHttpServletResponse mockResponse = new MockHttpServletResponse();

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with featureName missing from the header");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureNameMispelled=\"STATEMAN featureName from header\", " +
            "featureDescription=\"STATEMAN featureDescription from header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with only the required feature properties in the header");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"STATEMAN featureName from header\", " +
            "featureDescription=\"STATEMAN featureDescription from header\", "
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with only one product property in the header");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"REXX featureName from header\", " +
            "featureDescription=\"REXX featureDescription from header\", " +
            "productName=\"OPS productName From Header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with all feature and product properties in the header");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"REXX featureName from header\", " +
            "featureDescription=\"REXX featureDescription from header\", " +
            "productName=\"OPS productName From Header\", " +
            "productId=\"OPS productId From Header\", " +
            "version=\"OPS version 14 From Header\", " +
            "release=\"OPS release 2 From Header\", " +
            "modLevel=\"OPS modLevel 3 From Header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with all product and feature props in header and URL for only recording SCRT");
        mockRequest = createMockRequest(true);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"REXX featureName from header\", " +
            "featureDescription=\"REXX featureDescription from header\", " +
            "productName=\"OPS productName From Header\", " +
            "productId=\"OPS productId From Header\", " +
            "version=\"OPS version 14 From Header\", " +
            "release=\"OPS release 2 From Header\", " +
            "modLevel=\"OPS modLevel 3 From Header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with only feature props in header and URL for only recording SCRT");
        mockRequest = createMockRequest(true);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"AAA featureName from header\", " +
            "featureDescription=\"AAA featureDescription from header\", "
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with URL for only recording SCRT but no header");
        mockRequest = createMockRequest(true);
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with null ScrtProps parameter");
        FrsResult recordUseResult = new JfrsZosWriter().recordFeatureUse(null);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with null and blank feature properties");
        ScrtProps scrtPropsFromPgm = new ScrtProps(null, "   ");
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with all product and feature properties");
        scrtPropsFromPgm = new ScrtProps("featNameFromPgm", "featDescFromPgm");
        scrtPropsFromPgm.setProductInfo(
            "prodNameFromPgm", "prodIdFromPgm", "ver_11_FromPgm", "rel_6_FromPgm",
            "modLevel_25_FromPgm"
        );
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Calling recordFeatureUse with same feature within 1 day should *NOT* record SCRT");
        Thread.sleep(2000);
        scrtPropsFromPgm = new ScrtProps("featNameFromPgm", "featDescFromPgm");
        scrtPropsFromPgm.setProductInfo(
            "prodNameFromPgm", "prodIdFromPgm", "ver_11_FromPgm", "rel_6_FromPgm",
            "modLevel_25_FromPgm"
        );
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );
        System.out.println("______________________________________________________________");
    }

    // ________________________________________________________________________________
    private static MockHttpServletRequest createMockRequest(boolean useUrlForOnlyScrt) {
        MockHttpServletRequest mockRequest = new MockHttpServletRequest();
        mockRequest.setMethod("GET");
        mockRequest.setServerName("GeneMachine");
        mockRequest.setContextPath("/GeneContextPath");
        if (useUrlForOnlyScrt) {
            mockRequest.setServletPath(ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL);
        } else {
            mockRequest.setServletPath("/apiv1/RealAppURL");
        }
        return mockRequest;
    }

    // ________________________________________________________________________________
    private static void showInterceptResult(boolean interceptResult) {
        System.out.println("\ninterceptResult = " + interceptResult + "  ->  " +
            (
                interceptResult ? "This request is being sent to the product REST service." :
                "This request is *NOT* sent to any REST service."
            )
        );
    }

} // end App class
