/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import org.example.JfrsSdkRcException;

public class App {

    public static void main(String[] args) throws Exception {
        MockHttpServletRequest mockRequest;
        boolean interceptResult;
        Object handlerObj = new Object();

        MockHttpServletResponse mockResponse = new MockHttpServletResponse();

        /* zzz start comment

        zzz end comment */

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with no featureName in the header. Expect error.\n");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureNameMispelled=\"STATEMAN featureName from header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with only the featureName in the header. Expect success.\n");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"STATEMAN featureName from header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with only productId in the header. Expect error.\n");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"REXX featureName from header\", " +
            "productId=\"pIdHdr\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with all feature and product properties in the header. Expect success.\n");
        mockRequest = createMockRequest(false);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"REXX featureName from header\", " +
            "productId=\"pIdHdr\", " +
            "productVersion=\"14.2.3\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with URL '" + ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL +
            "' and no header. Expect error.\n"
        );
        mockRequest = createMockRequest(true);
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with URL '" + ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL +
            "' and no product props in header. Expect error.\n"
        );
        mockRequest = createMockRequest(true);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"AAA featureName from header\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call interceptor with URL '" + ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL +
            "' and all product and feature props in header. Expect success.\n"
        );
        mockRequest = createMockRequest(true);
        mockRequest.addHeader("Zowe-SCRT-client-feature",
            "featureName=\"OPS featureName from header for " + ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL + " \", " +
            "productId=\"pIdHdr\", " +
            "productVersion=\"14.2.3\""
        );
        interceptResult = new ScrtFeatHeaderInterceptor().preHandle(
            (MockHttpServletRequest) mockRequest, (HttpServletResponse) mockResponse, handlerObj
        );
        showInterceptResult(interceptResult);

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with null ScrtProps parameter. Expect Error.\n");
        FrsResult recordUseResult = new JfrsZosWriter().recordFeatureUse(null);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with null feature name. Expect Error.\n");
        ScrtProps scrtPropsFromPgm = null;
        try {
            scrtPropsFromPgm = new ScrtProps(null);
            System.out.println("\nScrtProps with null feature name should have thrown an exception. We should not reach this statement!!!");
        } catch (JfrsSdkRcException except) {
            FrsResult scrtResult = except.getFrsResult();
            System.out.println("Properly caught exception: RC = " + scrtResult.getRc() +
                " rsn = " + scrtResult.getRsn()
            );
        }
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with blank feature name. Expect Error.\n");
        try {
            scrtPropsFromPgm = new ScrtProps("   ");
            System.out.println("\nScrtProps with blank feature name should have thrown an exception. We should not reach this statement!!!");
        } catch (JfrsSdkRcException except) {
            FrsResult scrtResult = except.getFrsResult();
            System.out.println("Properly caught exception: RC = " + scrtResult.getRc() +
                " rsn = " + scrtResult.getRsn()
            );
        }
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Call recordFeatureUse with all product and feature properties. Expect success.\n");
        scrtPropsFromPgm = new ScrtProps("featNameFromPgm");
        scrtPropsFromPgm.setProductInfo("pIdPgm", "14.15.16");
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );

        System.out.println("______________________________________________________________");
        System.out.println("Calling recordFeatureUse with same feature within 1 day should *NOT* record SCRT\n");
        Thread.sleep(2000);
        scrtPropsFromPgm = new ScrtProps("featNameFromPgm");
        scrtPropsFromPgm.setProductInfo("pIdPgm", "14.15.16");
        recordUseResult = new JfrsZosWriter().recordFeatureUse(scrtPropsFromPgm);
        System.out.println("\nFrsResult rc = " + recordUseResult.getRc() +
            " rsn = " + recordUseResult.getRsn()
        );
        System.out.println("______________________________________________________________");

        /* zzz start comment

        zzz end comment */
    }

    // ________________________________________________________________________________
    private static MockHttpServletRequest createMockRequest(boolean useUrlForOnlyScrt) {
        MockHttpServletRequest mockRequest = new MockHttpServletRequest();
        mockRequest.setMethod("GET");
        mockRequest.setServerName("GeneMachine");
        mockRequest.setContextPath("/GeneContextPath");
        if (useUrlForOnlyScrt) {
            mockRequest.setServletPath(ScrtFeatHeaderInterceptor.ONLY_RECORD_SCRT_URL);
        } else {
            mockRequest.setServletPath("/api/v1/RealAppURL");
        }
        return mockRequest;
    }

    // ________________________________________________________________________________
    private static void showInterceptResult(boolean interceptResult) {
        System.out.println("\ninterceptResult = " + interceptResult + "  ->  " +
            (
                interceptResult ? "This request is being sent to the product REST service." :
                "This request is *NOT* sent to any REST service."
            )
        );
    }

} // end App class
