/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HttpsResponse {
  statusCode: number
  headers: Record<string, string>
  body: Array<number>
}
export interface Credential {
  account: string
  password: string
}
export function deletePassword(service: string, account: string): Promise<boolean>
export function findCredentials(service: string): Promise<Array<Credential>>
export function findPassword(service: string): Promise<string | null>
export function getCertificate(service: string, account: string): Promise<Buffer | null>
export function getPrivateKey(service: string, account: string): Promise<Buffer | null>
export function getPassword(service: string, account: string): Promise<string | null>
export function setPassword(service: string, account: string, password: string, persistWin32?: number | undefined | null): Promise<void>
export function createIdentityContext(service: string, account: string): Promise<string | null>
export function signWithIdentity(handleId: string, algorithm: string, data: Array<number>): Promise<Buffer | null>
export function releaseIdentityContext(handleId: string): Promise<boolean>
export interface NativeHttpsRequestOptions {
  hostname: string
  port: number
  path: string
  method: string
  headers: Record<string, string>
  body?: Array<number>
  certAccount: string
  rejectUnauthorized: boolean
  timeout?: number
}
export function nativeHttpsRequest(options: NativeHttpsRequestOptions): Promise<HttpsResponse>
