/*
* This program and the accompanying materials are made available under the terms of the
* Eclipse Public License v2.0 which accompanies this distribution, and is available at
* https://www.eclipse.org/legal/epl-v20.html
*
* SPDX-License-Identifier: EPL-2.0
*
* Copyright Contributors to the Zowe Project.
*
*/

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Credential {
  account: string
  password: string
}
export function deletePassword(service: string, account: string): Promise<boolean>
export function findCredentials(service: string): Promise<Array<Credential>>
export function findPassword(service: string): Promise<string | null>
export function getPassword(service: string, account: string): Promise<string | null>
export function setPassword(service: string, account: string, password: string): Promise<void>
