#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

MSYS_NO_PATHCONV=1 exec node "$basedir/../../../packages/cli/lib/main.js" "$@"
