defaultProfile: lpar1_zosmf
configuration:
    type: zosmf
    schema:
        type: object
        title: 'z/OSMF Profile'
        description: 'z/OSMF Profile'
        properties:
            host:
                type: string
                optionDefinition:
                    name: host
                    aliases:
                        - H
                    description: 'The z/OSMF server host name.'
                    type: string
                    required: true
                    group: 'Zosmf Connection Options'
            port:
                type: number
                optionDefinition:
                    name: port
                    aliases:
                        - P
                    description: 'The z/OSMF server port.'
                    type: number
                    defaultValue: 443
                    group: 'Zosmf Connection Options'
            user:
                type: string
                secure: true
                optionDefinition:
                    name: user
                    aliases:
                        - u
                    description: 'Mainframe (z/OSMF) user name, which can be the same as your TSO login.'
                    type: string
                    required: true
                    group: 'Zosmf Connection Options'
            password:
                type: string
                secure: true
                optionDefinition:
                    name: password
                    aliases:
                        - pass
                        - pw
                    description: 'Mainframe (z/OSMF) password, which can be the same as your TSO password.'
                    type: string
                    group: 'Zosmf Connection Options'
                    required: true
            rejectUnauthorized:
                type: boolean
                optionDefinition:
                    name: reject-unauthorized
                    aliases:
                        - ru
                    description: 'Reject self-signed certificates.'
                    type: boolean
                    defaultValue: true
                    group: 'Zosmf Connection Options'
            basePath:
                type: string
                optionDefinition:
                    name: base-path
                    aliases:
                        - bp
                    description: 'The base path for your API mediation layer instance. Specify this option to prepend the base path to all z/OSMF resources when making REST requests. Do not specify this option if you are not using an API mediation layer.'
                    type: string
                    group: 'Zosmf Connection Options'
        required:
            - host
    createProfileExamples:
        -
            options: 'zos123 --host zos123 --port 1443 --user ibmuser --password myp4ss'
            description: 'Create a zosmf profile called ''zos123'' to connect to z/OSMF at host zos123 and port 1443'
        -
            options: 'zos124 --host zos124 --user ibmuser --password myp4ss --reject-unauthorized false'
            description: 'Create a zosmf profile called ''zos124'' to connect to z/OSMF at the host zos124 (default port - 443) and allow self-signed certificates'
